#!/usr/bin/env python

import sys
reload(sys)
sys.setdefaultencoding("utf-8")
from time import sleep
from selenium import webdriver

def usage(message=None, exit_code=0):
    if message:
        print >> sys.stderr, message
    print "usage: %s BROWSER URL" % sys.argv[0]
    if exit:
        sys.exit(exit_code)

if len(sys.argv) < 3:
    usage("Too few arguments", exit_code=1)

browser = sys.argv[1]
url = sys.argv[2]

browsers = {"chrome":webdriver.Chrome,
            "firefox":webdriver.Firefox,
#            "ie":webdriver.IE,
            "opera":webdriver.Opera}

if browser not in browsers:
    print >> sys.stderr, "Unknown browser: %s" % browser
    sys.exit(1)

driver_cls = browsers[browser]
driver = driver_cls()

driver.get(url)
print u"%s" % driver.page_source
driver.quit()
