#!/bin/bash

if [ -z "$ECHNIDA_TOKEN" ]
then
	>&2 echo "$0: error: ECHNIDA_TOKEN not set"
	exit 65
fi

curl https://labs.w3.org/echidna/api/request \
	--data "url=https://w3c.github.io/webdriver/echidna-manifest.txt" \
	--data "decision=https://lists.w3.org/Archives/Public/public-browser-tools-testing/2015JulSep/0009.html" \
	--data "token=$ECHNIDA_TOKEN"
