#!/bin/sh

file=$1 || "index.html"
if [ -z $file ]; then
	file="index.html"
fi

errs=$(curl -s -F laxtype=yes \
		-F parser=html5 \
		-F level=error \
		-F out=gnu \
		-F doc=@$file \
		"https://validator.w3.org/nu/" \
	| sed -e 's/"//g')
echo $errs
test -z "$errs"
